import axios from "axios";

// REACT_APP_API_URL is baked in at build time:
//   Docker production → /api  (proxied by nginx to PHP backend)
//   Local XAMPP dev   → http://localhost/mini-automation/backend/api
const BASE = process.env.REACT_APP_API_URL
  || "http://localhost/mini-automation/backend/api";

const api = axios.create({ baseURL: BASE });

export const login = (email, password) =>
  api.post("/login.php", { email, password });

export const createJob = (data) =>
  api.post("/create-job.php", data);

export const getJobs = (status = "") =>
  api.get("/jobs.php", { params: status ? { status } : {} });

export const getJobDetail = (id) =>
  api.get("/job-detail.php", { params: { id } });

export const getLogs = (job_id = "") =>
  api.get("/logs.php", { params: job_id ? { job_id } : {} });

// Legacy download (dummy portal flow)
export const downloadUrl = (id) =>
  `${BASE}/download.php?id=${id}`;

// Download barcode file generated by bot
export const downloadFileUrl = (id) =>
  `${BASE}/download-file.php?id=${id}`;

export const bulkCreateJobs = (jobs) =>
  api.post("/bulk-create-jobs.php", { jobs });

export const sampleTemplateUrl = () =>
  `${BASE}/sample-template.php`;

export const getCompanies = () =>
  api.get("/companies.php");

export const getParts = () =>
  api.get("/parts.php");

export const resetFailedJobs = () =>
  api.post("/reset-failed-jobs.php", {});

// ── New Excel import flow ─────────────────────────────────────

// Step 1: Send file to backend → get preview with valid/invalid rows
export const uploadExcelPreview = (file) => {
  const form = new FormData();
  form.append("file", file);
  form.append("action", "preview");
  return api.post("/upload-excel.php", form, {
    headers: { "Content-Type": "multipart/form-data" },
  });
};

// Step 2: Upload supporting files (PDF/JPG/PNG/ZIP) to a batch folder
// Returns: { success, batch_id, files: [{name, path}] }
export const uploadSupportFiles = (filesFormData) =>
  api.post("/upload-support-files.php", filesFormData, {
    headers: { "Content-Type": "multipart/form-data" },
  });

// Step 3: Send validated rows + batch_id → insert jobs in DB
// Server maps Excel filenames to server paths using batch_id folder
export const importJobs = (rows, batchId = "") =>
  api.post("/upload-excel.php", { action: "import", rows, batch_id: batchId });

// Downloads list (jobs with barcode files)
export const getDownloads = () =>
  api.get("/downloads.php");

// Field mappings for a company (used by bot — exposed for debugging)
export const getFieldMappings = (company) =>
  api.get("/field-mappings.php", { params: { company } });

// ── Bot error tracking ────────────────────────────────────
// Returns bot_error_logs rows with optional filters:
//   { company_name, field_key, error_type, date_from, date_to, job_id, limit }
export const getBotErrors = (params = {}) =>
  api.get("/bot-errors.php", { params });
